blog/urls.py
from django.urls import path
from .import views
from .views import PostListView, SearchResultsListView

from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # path('', PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('search/', SearchResultsListView.as_view(), name='search_results'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
            .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, related_name='blog_posts', on_delete=models.CASCADE,)
    body = models.TextField()
    cover = models.ImageField(upload_to='covers/', blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[
            self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug
        ])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by{self.name} on {self.post}."

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.db.models import Q

from taggit.models import Tag
from .forms import EmailPostForm, CommentForm

from .models import Post, Comment


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'post/list.html', {'page': page,
                                              'posts': posts,
                                              'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-publish')[:4]

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'post/detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'hellruler80@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post, 'form': form, 'sent': sent})


class SearchResultsListView(ListView):
    model = Post
    context_object_name = 'posts'
    paginate_by = 10
    template_name = 'post/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q',)
        return Post.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        )

templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title> {% block title %} {% endblock title%} </title>
</head>

<body>
    <div id="content">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/inc/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

templates/inc/pagination.html
<div class="pagination" aria-label="Page navigation example">
    <ul class="pagination">
        {% if page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        <li class="page-item"><a class="page-link" href="#">{{ page.number }}</a></li>
        {% if page.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</div>

templates/inc/sidebar.html
{% load blog_tags %}

<div class="col-md-6" style="float:right; max-width:600px">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <span class="fs-5 fw-semibold">My Blog</span>
            </a><br>
            <div class="col-10 mb-1 small">This is my blog. I've written {% total_posts %} posts so
                far.</div>
            <hr>
            <div class="list-group">
                <div class="list-group-item list-group-item-action active py-3 lh-tight" aria-current="true">
                    <div class="d-flex w-100 align-items-center justify-content-between">
                    </div>
                    <h3>Latest Posts</h3>
                </div>
                {% show_latest_posts 3 %}
                <div class="list-group-item list-group-item-action active py-3 lh-tight" aria-current="true">
                    <div class="d-flex w-100 align-items-center justify-content-between">
                    </div>
                    <h3>Most commented posts</h3>
                </div>
                {% get_most_commented_posts as most_commented_posts %}
                <ul>
                    {% for post in most_commented_posts %}
                    <li>
                        <a href=" {{ post.get_absolute_url }} ">{{ post.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
                <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></ p>
            </div>
        </div>
    </div>
</div>

templates/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% load crispy_forms_tags %}

{% load blog_tags %}

{% block content %}

<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <button class="btn btn-outline-success" type="button"><a href="{% url 'blog:post_list' %}">Back</a></button>
    <div class="col-md-6 px-0">
        <h1 class="display-4 fst-italic">{{ post.title }}</h1>
        <p class="lead my-3">{{ post.body|markdown }}</p>
        <div class="mb-1 text-muted">{{ post.publish }}</div>
        <p class="lead mb-0"><a href="{% url 'blog:post_share' post.id %}" class="text-white fw-bold">Share</a></p>
        <div class="col-auto d-none d-lg-block" style="float: right;">
            <img class="img" src="{{ post.cover.url }}" width="200" height="250" style="float:right; max-width:600px"
                aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
            <title>Placeholder</title>
            </img>
        </div>
    </div>
</div>
<div class="similarpost mx-2">
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}
</div>

<div class="numcomment mx-3">
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}
</div>

<div class="commentdetail mx-5">
    {% for comment in comments %}
    <div class="comment">
        <p class="info text-muted"><small>
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}</small>
        </p>
        {{ comment.body|linebreaks }}
        <hr>
    </div>
    {% empty %}
    <p>There are no comments yet.</p>
    {% endfor %}
</div>

<div class="container mx-5">
    {% if new_comment %}
    <h2>Your comment has been added.</h2>
    {% else %}
    <h2>Add a new comment</h2>
    <form action="." method="post">
        {% csrf_token %}
        {{ comment_form|crispy }}
        <p><input class="btn btn-outline-success" type="submit" value="Add comment"></p>
    </form>
</div>
{% endif %}

{% endblock %}

templates/post/list.html
{% extends 'blog/base.html' %}

{% block title %}My Blog{% endblock title %}

{% block content %}

{% load blog_tags %}

<div class container>
    {% csrf_token %}
    <form class="form-inline mt-2 mt-md-0" action="{% url 'blog:search_results' %}" method="get">
        <input name="q" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
    </form>
</div>
<hr>
{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% include 'inc/sidebar.html' %}

{% for post in posts %}
<div class='tag'>
    <p class="tags">Tags:
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
</div>
<div class="col mb-2" style="max-width:1400px">
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-success">{{ post.author }}</strong>
                <h3 class="mb-0 text-decoration-none"><a class="anchor text-decoration-none"
                        href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h3>
                <div class='tag'>
                    <p class="tags">Tags:
                        {% for tag in post.tags.all %}
                        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                </div>
                <div class="mb-1 text-muted">{{ post.publish }}
                </div>
                {% autoescape off %}
                <p class="mb-auto">{{ post.body|markdown|truncatewords_html:30 }}</p>
                {% endautoescape %}
                <a href="{{ post.get_absolute_url }}" class="stretched-link">Continue reading</a>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img class="img" src="{{ post.cover.url }}" width="300" height="250" aria-label="Placeholder: Thumbnail"
                    preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Imageholder</title>
                </img>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% include  "inc/pagination.html" with page=posts %}

{% endblock content %}

templates/post/search_results.html
{% extends 'blog/base.html' %}

{% block title %}Search{% endblock title %}

{% block content %}

<h1>Search Results</h1>

{% for post in posts %}
<div>
    <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
    <p>Author: {{ post.author }}</p>
</div>
{% endfor %}
{% endblock content %}

templates/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ cd.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
    {{ form|crispy }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}

{% endblock %}